/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#45464d",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#6bd8cb",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006f66",
        tertiary: "#000000",
        "tertiary-container": "#2a1700",
        "inverse-surface": "#213145",
        "on-secondary-fixed": "#00201d",
        "on-primary-container": "#7c839b",
        "tertiary-fixed": "#ffddb8",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        background: "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        surface: "#f8f9ff",
        "inverse-primary": "#bec6e0",
        "on-tertiary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#89f5e7",
        "secondary-container": "#86f2e4",
        primary: "#000000",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#005049",
        "outline-variant": "#c6c6cd",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        outline: "#76777d",
        "on-primary-fixed": "#131b2e",
        secondary: "#006a61",
        "primary-container": "#131b2e",
        "error-container": "#ffdad6",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#2a1700",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#bec6e0",
        "surface-tint": "#565e74",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-container": "#b87500",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        lg: "24px",
        "container-max": "1440px",
        base: "4px",
        sm: "8px",
        xs: "4px",
        gutter: "20px",
        xl: "32px",
      },
      fontFamily: {
        "headline-sm": ["var(--font-inter)"],
        "label-caps": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "data-tabular": ["var(--font-jetbrains-mono)"],
        "headline-md": ["var(--font-inter)"],
        "display-lg": ["var(--font-inter)"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-tabular": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
